add control detector logic
zooyeon/LgCannonDemoCodeDist pull request #8
Opened 2024-06-24 23:49 UTC by phuongdv88

create and delete detector when start/stop the client handling thread

2024-06-24 23:49 UTC, phuongdv88 commented
Please don't merge it until I test it tomorrow afternoon

2024-06-25 21:42 UTC, phuongdv88 commented
Dear @zooyeon  It's ready to merge

2024-06-26 00:45 UTC, zooyeon requested changes
@phuongdv88 why do you want to delete LgClientController.exe?

2024-06-26 00:45 UTC, zooyeon commented on LgClientDisplay_python/dist/LgClientController.exe
@phuongdv88 
do you want to delete LgClientContoroller.exe?

@rdg5924

2024-06-26 00:46 UTC, phuongdv88 commented on LgClientDisplay_python/dist/LgClientController.exe
@zooyeon my antivirus app deleted it. Not me

2024-06-26 01:09 UTC, zooyeon commented on LgClientDisplay_python/dist/LgClientController.exe
@phuongdv88 Okay, but please do not include it in the commits.

2024-06-26 01:41 UTC, merged